import * as fs from 'fs';
import * as path from 'path';
import { LogPlayer } from '../src/agent/logger/LogPlayer';

// 取最新的一个 agent-log 文件
const dir = path.join(process.cwd(), 'agent-log');
const file = fs.readdirSync(dir)
  .filter(f => f.endsWith('.log'))
  .map(f => ({ f, t: fs.statSync(path.join(dir, f)).mtimeMs }))
  .sort((a, b) => b.t - a.t)[0]?.f;
if (!file) throw new Error('no agent-log found');

const entries = new LogPlayer({ logFilePath: path.join(dir, file) }).parseLogFile();

// 每种 type 取第一条 message
const byType = new Map<string, unknown>();
for (const e of entries) {
  const m = e.message as { type?: string };
  if (m && typeof m.type === 'string' && !byType.has(m.type)) {
    byType.set(m.type, m);
  }
}

const samples = Object.fromEntries(byType);
const out = path.join(process.cwd(), 'src/components/demo/sample-messages.ts');
fs.mkdirSync(path.dirname(out), { recursive: true });
fs.writeFileSync(
  out,
  '// AUTO-GENERATED by scripts/extract-demo-samples.ts — real recorded samples, one per type.\n'
  + 'import type { StreamCallbackMessage } from \'@/types\';\n\n'
  + 'export const SAMPLE_MESSAGES: StreamCallbackMessage[] = '
  + JSON.stringify(Object.values(samples), null, 2)
  + ' as unknown as StreamCallbackMessage[];\n',
);
console.log('Wrote', Object.keys(samples).length, 'sample types:', Object.keys(samples).join(', '));
